### PR TITLE
add direnv

### PR DESCRIPTION
**Pull request by waalge**
It took too many hours to get a working dev shell. It should have taken ~2 minutes.

I don't expect this PR to be accepted, but for the next person looking for a way to do it without working through 10 ways how not to do it, here's a suggestion

### CODE REVIEW

**Comment by KtorZ** [comment]
I do actually use direnv locally too and automatically triggering: 

> use flake "github:CardanoSolutions/devx#ghc96-iog"

.. is... no 😅! 

But. I am happy to add that somewhere in the `CONTRIBUTING.md`. Kupo is getting a lot more attention lately from contributors, and I think it's time to make the dev environment around it a bit more accessible.

**Comment by waalge** [comment]
@KtorZ Any objections adding `.direnv/` to the gitignore?

I know you've showed me alternative ways to do it. 
Unfortunately, tools like helix did consult `.gitignore` but not `.git/info/exclude` when deciding what to make searchable.

**Comment by KtorZ** [comment]
> @KtorZ Any objections adding .direnv/ to the gitignore?

Nope!

**Comment by KtorZ** [comment]
>  tools like helix did consult .gitignore

Do you know if they also look for your system-level gitignore perhaps ?

**Comment by waalge** [comment]
I'll look into it

**Pull request closed without merging**
